carts/urls.py
from django.urls import path
from . import views
from .models import Cart, CartItem

urlpatterns = [

    path('',views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),#<int will dynamically mapp to product_id
    path('reduce_cart_items/<int:product_id>/<int:cart_item_id>/', views.reduce_cart_items, name='reduce_cart_items'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),

]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.home, name="home"),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from .models import Product
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),

]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account



class Cart(models.Model):
    
    cart_id = models.CharField(max_length=50,blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id
    
class CartItem(models.Model):


    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    products = models.ForeignKey(Product,on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey (Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.products.price * self.quantity
    

    def __unicode__(self):
        return self.products

store/models.py
from django.db import models
from django.urls import reverse
from category.models import Category


class Product(models.Model):

    product_name = models.TextField(max_length=100,unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=50, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now_add=True)
    
    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name




class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variation_category='color',is_active=True)

    def size(self):
        return super(VariationManager,self).filter(variation_category='size',is_active=True)




variation_category_choice = (
    ('color', 'color'),
    ('size', 'size'),
)

class Variation(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)


    objects = VariationManager()

    def __str__(self):
        return self.variation_value















# to save slugs using title fields and has an increment for ensuring uniqueness
# def save(self, *args, **kwargs):
#     if not self.slug:
#         base_slug = slugify(self.title)
#         slug = base_slug
#         count = 1

#         while Article.objects.filter(slug=slug).exists():
#             slug = f"{base_slug}-{count}"
#             count += 1

#         self.slug = slug

#     super().save(*args, **kwargs)

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Cart, CartItem
from store.models import Product, Variation
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from accounts.views import login

# returns a unique cart id for current session , a user may not be logged in but still imp to identify their cart
def _cart_id(request):
    cart = request.session.session_key #ask browser for existing key
    if not cart:
        cart = request.session.create() #if there isn't one, create one
    return cart

#this part will handle the cart actions like 
# 1. adding a product to the cart, if cart dont exists we create one
# 2. if there is a product already increase the quantity#

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    current_user = request.user

    # --------------------------------------------------
    # STEP 1: Collect product variations from POST
    # --------------------------------------------------
    product_variation = []

    if request.method == "POST":
        for key, value in request.POST.items():
            try:
                variation = Variation.objects.get(
                    product=product,
                    variation_category__iexact=key,
                    variation_value__iexact=value
                )
                product_variation.append(variation)
            except:
                pass

    # --------------------------------------------------
    # STEP 2: Decide cart owner (USER or SESSION CART)
    # --------------------------------------------------
    cart = None
    if not current_user.is_authenticated:
        cart, _ = Cart.objects.get_or_create(cart_id=_cart_id(request))

    # --------------------------------------------------
    # STEP 3: Fetch cart items for this product & owner
    # --------------------------------------------------
    if current_user.is_authenticated:
        cart_items = CartItem.objects.filter(
            products=product,
            user=current_user
        )
    else:
        cart_items = CartItem.objects.filter(
            products=product,
            cart=cart
        )

    # --------------------------------------------------
    # STEP 4: Match variations
    # --------------------------------------------------
    ex_var_list = []
    item_ids = []

    for item in cart_items:
        ex_var_list.append(list(item.variations.all()))
        item_ids.append(item.id)

    # --------------------------------------------------
    # STEP 5: Increase quantity OR create new cart item
    # --------------------------------------------------
    if product_variation in ex_var_list:
        index = ex_var_list.index(product_variation)
        item = CartItem.objects.get(id=item_ids[index])
        item.quantity += 1
        item.save()
    else:
        cart_item = CartItem.objects.create(
            products=product,
            quantity=1,
            user=current_user if current_user.is_authenticated else None,
            cart=None if current_user.is_authenticated else cart
        )
        if product_variation:
            cart_item.variations.add(*product_variation)
        cart_item.save()

    return redirect('cart')





# to reduce the cart items
def reduce_cart_items(request, product_id, cart_item_id):
    products = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(id=cart_item_id, user=request.user, products=products)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(id=cart_item_id, cart=cart, products=products)
    if cart_item:
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    
    return redirect('cart')


# to remove the entire product
def remove_cart_item(request, product_id,cart_item_id):
    products = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        CartItem.objects.filter(products=products, user=request.user, id=cart_item_id).delete()
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        CartItem.objects.filter(products=products, cart=cart, id=cart_item_id).delete()

    return redirect('cart')




def cart(request, total=0, quantity=0, cart_items=None):
    
    try:
        tax = 0
        grand_total = 0

        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id = _cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.products.price * cart_item.quantity)
            quantity += cart_item.quantity

        tax = (2 * total) / 100
        grand_total = tax + total
    except ObjectDoesNotExist:
        pass
    
    context = {
        'total':total,
        'quantity':quantity,
        'cart_items':cart_items,
        'tax':tax,
        'grand_total': grand_total,

    }

    return render(request, 'store/cart.html', context)


@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_item=None):
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.products.price * cart_item.quantity)
            quantity += cart_item.quantity

        tax = (2 * total) / 100
        grand_total = tax + total
    except ObjectDoesNotExist:
        pass
        
    context = {
        'total':total,
        'quantity':quantity,
        'cart_items':cart_items,
        'tax':tax,
        'grand_total': grand_total,

    }

    return render(request, 'store/checkout.html', context )

store/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Product
from category.models import Category
from carts.models import Cart, CartItem
from carts.views import _cart_id
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator


def store(request, category_slug=None):
    categories=None
    products=None
    page = request.GET.get('page')

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        # paginator = Paginator(products, 1)
        # page = request.GET.get('page')
        # paged_products = paginator.get_page(page)
        

    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')

    paginator = Paginator(products, 3)
    paged_products = paginator.get_page(page)
    product_count = products.count()
 
    context = {
        'products':paged_products,
        'product_count': product_count,
    }
    return render(request, 'store/store.html', context)



def product_detail(request, category_slug, product_slug):
        try:
            single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
            in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), products = single_product).exists()
        
        except Exception as e:
            raise e

        context = {
             'single_product':single_product,
             'in_cart':in_cart,

        }
        
        return render(request,'store/product_detail.html',context)


def search(request):
    # this will check if the keyword is in the url
    if 'keyword' in request.GET:

        #this will get the value entered in the search
        keyword = request.GET['keyword']

        #to ensure the keyword isnt empty
        if keyword:
            products = Product.objects.order_by("created_date").filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            # here we use order by to show newest first and using query sets we can filter out

            product_count = products.count()

    context = {
        'products':products,
        'product_count': product_count,
    }

    return render(request, 'store/store.html', context)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items %}

<h2>Your Cart is Empty !!</h2>
<br>
<div class= "text-center">
	<a href="{% url 'store' %}" class="btn btn-primary"> Continue Shopping</a>
</div>


{% else %}
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>

{% for cart_item in cart_items %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{ cart_item.products.images.url }}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{ cart_item.products.get_url }}" class="title text-dark">{{cart_item.products.product_name}}</a>
				<p class="text-muted small">

					{% if cart_item.variations.exists %} <!--check if the item has variations linked-->
					   {% for item in cart_item.variations.all %} <!--see now for all the variation in it -->
					   {{item.variation_category | capfirst }} : {{item.variation_value | capfirst}} <br> <!--this shows the variation with captial letter first-->
                       {% endfor %}
					{% endif %}
				</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
			<div class="col">
    <div class="input-group input-spinner">

        <!-- minus button -->
        <div class="input-group-prepend">
        <a href="{% url 'reduce_cart_items' cart_item.products.id cart_item.id %}" class="btn btn-light" type="button" id="button-minus">
                <i class="fa fa-minus"></i>
            </a> 
        </div>

        <!-- quantity -->
        <input type="text" class="form-control" value="{{ cart_item.quantity }}">

        <!-- plus button -->
        <div class="input-group-append">
			<form action="{% url 'add_cart' cart_item.products.id  %}" method="POST">
				{% csrf_token %}
				{% for item in cart_item.variations.all %}
				  <input type="hidden" name="{{item.variation_category | lower}}" value="{{item.variation_value | capfirst}}">
				{% endfor %}
				<button class="btn btn-light" type="submit" id="button-plus"><i class="fa fa-plus"></i></button>
			</form>
        </div>

    </div>
</div>

	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">{{cart_item.sub_total}}</var> 
			<small class="text-muted"> {{cart_item.products.price}} </small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
	<a href="{% url 'remove_cart_item' cart_item.products.id cart_item.id %}" onclick="return confirm ('U sure u want to delete?')" class ="btn btn-danger"> Remove</a>
	</td>
</tr>
{% endfor %}
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">{{total}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> {{tax}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Grand Total:</dt>
			  <dd class="text-right text-dark b"><strong>{{grand_total}}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
{% endif %}
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-content padding-y bg">
<div class="container">

<div class="row">

  <!-- ================= LEFT : BILLING ADDRESS ================= -->
  <aside class="col-lg-6">
    <div class="card">
      <div class="card-body">

        <h4 class="card-title mb-4">Billing Address</h4>

        <form action="{%url 'place_order' %}" method="post">

            {% csrf_token %}

          <div class="form-row">
            <div class="col form-group">
              <label>First Name</label>
              <input type="text" name="first_name" class="form-control">
            </div>
            <div class="col form-group">
              <label>Last Name</label>
              <input type="text" name="last_name" class="form-control">
            </div>
          </div>

          <div class="form-row">
            <div class="col form-group">
              <label>Email</label>
              <input type="email" name="email" class="form-control">
            </div>
            <div class="col form-group">
              <label>Phone Number</label>
              <input type="text" name="phone" class="form-control">
            </div>
          </div>

          <div class="form-row">
            <div class="col form-group">
              <label>Address Line 1</label>
              <input type="text" name="address_line_1" class="form-control">
            </div>
            <div class="col form-group">
              <label>Address Line 2</label>
              <input type="text" name="address_line_2" class="form-control">
            </div>
          </div>

          <div class="form-row">
            <div class="col form-group">
              <label>City</label>
              <input type="text" name="city" class="form-control">
            </div>
            <div class="col form-group">
              <label>State</label>
              <input type="text" name="state" class="form-control">
            </div>
            <div class="col form-group">
              <label>Country</label>
              <input type="text" name="country" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label>Order Note</label>
            <textarea name="order_note" rows="4" class="form-control"></textarea>
          </div>

      

      </div>
    </div>
  </aside>

  <!-- ================= RIGHT : CART SUMMARY ================= -->
  <aside class="col-lg-6">

    <div class="card">
      <div class="card-body">

        <table class="table table-borderless table-shopping-cart">
          <thead class="text-muted">
            <tr class="small text-uppercase">
              <th>Product</th>
              <th width="120">Quantity</th>
              <th width="120">Price</th>
            
            </tr>
          </thead>

          <tbody>
          {% for cart_item in cart_items %}
          <tr>
            <td>
              <figure class="itemside align-items-center">
                <div class="aside">
                  <img src="{{ cart_item.products.images.url }}" class="img-sm">
                </div>
                <figcaption class="info">
                  <a href="{{ cart_item.products.get_url }}" class="title text-dark">
                    {{ cart_item.products.product_name }}
                  </a>
                  <p class="text-muted small">
                    {% for item in cart_item.variations.all %}
                      {{ item.variation_category|capfirst }} :
                      {{ item.variation_value|capfirst }} <br>
                    {% endfor %}
                  </p>
                </figcaption>
              </figure>
            </td>

            <td>
              <input type="text" class="form-control text-center" value="{{ cart_item.quantity }}">
            </td>

            <td>
              <div class="price-wrap">
                <var class="price">{{ cart_item.sub_total }}</var>
                <small class="text-muted">{{ cart_item.products.price }}</small>
              </div>
            </td>

    
          </tr>
          {% endfor %}
          </tbody>
        </table>

        <button type="submit" name="submit" class="btn-primary btn-block">Place Order</button>
        
        <a href="{% url 'store' %}" class="btn btn-light btn-block">
          Continue Shopping
        </a>

      </div>
    </div>
    </form>

  </aside>

</div>
</div>
</section>

{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-content padding-y bg">
<div class="container">

<div class="card">
  <div class="row no-gutters">

    <aside class="col-md-6">
      <article class="gallery-wrap">
        <div class="img-big-wrap">
          <img src="{{ single_product.images.url }}">
        </div>
      </article>
    </aside>

    <main class="col-md-6 border-left">

      <!-- FORM START -->
      <form action="{% url 'add_cart' single_product.id %}" method="POST">
        {% csrf_token %}

        <article class="content-body">

          <h2 class="title">{{ single_product.product_name }}</h2>

          <div class="mb-3">
            <var class="price h4">{{ single_product.price }}</var>
          </div>

          <p>{{ single_product.description }}</p>

          <hr>

          <!-- COLOR -->
          <div class="row">
            <div class="item-option-select">
              <h6>Choose Color</h6>
              <select name="color" class="form-control" required>
                <option value="" disabled selected>Select</option>
                {% for i in single_product.variation_set.all %}
                  {% if i.variation_category == 'color' %}
                    <option value="{{ i.variation_value|lower }}">
                      {{ i.variation_value|capfirst }}
                    </option>
                  {% endif %}
                {% endfor %}
              </select>
            </div>
          </div>

          <!-- SIZE -->
          <div class="row">
            <div class="item-option-select">
              <h6>Select Size</h6>
              <select name="size" class="form-control" required>
                <option value="" disabled selected>Select</option>
                {% for i in single_product.variation_set.all %}
                  {% if i.variation_category == 'size' %}
                    <option value="{{ i.variation_value|lower }}">
                      {{ i.variation_value|capfirst }}
                    </option>
                  {% endif %}
                {% endfor %}
              </select>
            </div>
          </div>

          <hr>

          {% if single_product.stock <= 0 %}
            <h5 class="text-danger">Out of stock</h5>
          {% else %}
            <button type="submit" class="btn btn-primary">
              <span class="text">Add to cart</span>
              <i class="fas fa-shopping-cart"></i>
            </button>
          {% endif %}

        </article>
      </form>
      <!-- FORM END -->

    </main>

  </div>
</div>

</div>
</section>

{% endblock %}

templates/store/store.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>
</head>
<body>
{% block content %}
<section class="section-pagetop bg">
<div class="container">
	{% if 'search' in request.path %}
	<h2 class="title-page">Search Result</h2>

	{% else %}
	<h2 class="title-page">Our Store</h2>

	{% endif %}
	
</div> <!-- container //  -->
</section>

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
<div class="container">

<div class="row">
	<aside class="col-md-3">
		
<div class="card">
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Categories</h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_1" style="">
			<div class="card-body">
				
				<ul class="list-menu">
					<li><a href="{%url 'store'%}">All Products</a></li>
				{% for category in links%}
				    <li><a href="{{category.get_url}}">{{category.category_name}}  </a></li>
				{% endfor %}
				</ul>

			</div> <!-- card-body.// -->
		</div>
	</article> <!-- filter-group  .// -->
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Sizes </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_4" style="">
			<div class="card-body">
			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XS </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> SM </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> LG </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XXL </span>
			  </label>
		</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->
	
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Price range </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_3" style="">
			<div class="card-body">
				
				<div class="form-row">
				<div class="form-group col-md-6">
				  <label>Min</label>
				  <!-- <input class="form-control" placeholder="$0" type="number"> -->
				  	<select class="mr-2 form-control">
						<option value="0">$0</option>
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
					</select>
				</div>
				<div class="form-group text-right col-md-6">
				  <label>Max</label>
				  	<select class="mr-2 form-control">
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
						<option value="2000">$2000+</option>
					</select>
				</div>
				</div> <!-- form-row.// -->
				<button class="btn btn-block btn-primary">Apply</button>
			</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->
	
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<main class="col-md-9">

<header class="border-bottom mb-4 pb-3">
		<div class="form-inline">
			<span class="mr-md-auto">Found <b> {{product_count}} </b>Items</span>
			
		</div>
</header><!-- sect-heading -->

<div class="row">
	{% if products %}
	{% for product in products %}
	<div class="col-md-4">
		<figure class="card card-product-grid">
			<div class="img-wrap"> 
				
				<a href="{{product.get_url}}"><img src="{{product.images.url}}"></a>
				
			</div> <!-- img-wrap.// -->
			<figcaption class="info-wrap">
				<div class="fix-height">
					<a href="./product-detail.html" class="title">{{product.product_name}}</a>
					<div class="price-wrap mt-2">
						<span class="price">{{product.price}}</span>
					</div> <!-- price-wrap.// -->
				</div>
				<a href="{{product.get_url }}" class="btn btn-block btn-primary">View Details </a>
			</figcaption>
		</figure>
	</div> <!-- col.// -->
	{% endfor%}
	{% else %}
	<div><h2>Not Found</h2></div>
	{% endif %}
</div>




<nav class="mt-4" aria-label="Page navigation sample">
	{% if products.has_other_pages %}
  <ul class="pagination">

	{% if products.has_previous %}
	<li class="page-item"><a class="page-link" href="?page={{products.previous_page_number}}">Previous</a></li>
    
	{% else %}
   
	<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
   
	{% endif %}

	{% for i in products.paginator.page_range %}
	   {% if products.number == i %}
	     <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
		 {% else %}
		 <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
		 {% endif %}
    {% endfor %}

	{% if products.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{products.next_page_number}}">Next</a></li>
	{% else %}
	  <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
	{% endif %}
  </ul>
  {% endif %}
</nav>

	</main> <!-- col.// -->

</div>

</div> <!-- container .//  -->
</section>

    
{% endblock %}
</body>
</html>